language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - libcpprest-dev
            - qt5-default
      env: 
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

#    - os: osx
#      osx_image: xcode9.4


before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then eval "${MATRIX_EVAL}"; fi
 
before_script:
    - sudo find -name cpprestsdkConfig.cmake
    - sudo find -name cpprestsdk-config.cmake
    - mkdir build
    - cd build
    - cmake .. -DBUILD_RAPID_JSON:BOOL=ON -DBUILD_CPP_REST:BOOL=ON -DBUILD_CPP_REST:BOOL=ON -DBUILD_NLOHMANN:BOOL=ON -DBUILD_QT:BOOL=ON -Dcpprestsdk_DIR:PATH=/../cmake/cpprest/
  
script:
    - make
    - cd CerializerTests
    - ./CerializerTests
